version: '3.5'
services:
  sea-todos-mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: gotit
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sea_todos
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - sea-todos-mysql:/var/lib/mysql
    networks:
      - sea-todos
  sea-todos-redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sea-todos
  sea-todos-celery-worker:
    image: uendno/sea-todos-celery-worker:latest
    build:
      context: ./sea-todos-backend
      dockerfile: CeleryWorkerDockerfile
      args:
        ENV: ${ENV}
    depends_on:
      - sea-todos-redis
    environment:
      CELERY_BROKER_URL: redis://sea-todos-redis
    networks:
      - sea-todos
  sea-todos-backend:
    image: uendno/sea-todos-celery-backend:latest
    build:
      context: ./sea-todos-backend
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    depends_on:
      - sea-todos-redis
    environment:
       CELERY_BROKER_URL: redis://sea-todos-redis
    ports:
      - "8080:80"
    networks:
      - sea-todos
  sea-todos-frontend:
    image: uendno/sea-todos-celery-frontend:latest
    build:
      context: ./sea-todos-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_ENV: ${ENV}
    ports:
      - "3000:5000"
    networks:
      - sea-todos

volumes:
  sea-todos-mysql:
networks:
  sea-todos:
    driver: overlay