export const FILTER_OPTIONS = {
  ALL: 'all',
  ACTIVE: 'active',
  COMPLETED: 'completed'
}

export const ACTIONS = {
  GET_TASKS: 'GET_TASKS',
  GET_TASKS_COMPLETE: 'GET_TASKS_COMPLETE',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',
  TOGGLE_TASK: 'TOGGLE_TASK',
  TOGGLE_TASK_COMPLETE: 'TOGGLE_TASK_COMPLETE',
  TOGGLE_TASK_ERROR: 'TOGGLE_TASK_ERROR',
  ADD_TASK:'ADD_TASK',
  ADD_TASK_COMPLETE:'ADD_TASK_COMPLETE',
  ADD_TASK_ERROR: 'ADD_TASK_ERROR',
  SET_FILTER: 'SET_FILTER',
};
