class _Config(object):
    SQLALCHEMY_ECHO = False
    SQLALCHEMY_MAX_OVERFLOW = 0
    SQLALCHEMY_POOL_SIZE = 10
    SQLALCHEMY_RECORD_QUERIES = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    CELERY_VISIBILITY_TIMEOUT = 90000